#This script will add the auto increment to all the appropriate tables

SET foreign_key_checks = 0;

ALTER TABLE FileAttributes
	MODIFY COLUMN PK_FileAttributes_ID INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE Analysis
	MODIFY COLUMN PK_Analysis_ID INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE Sanitize
	MODIFY COLUMN PK_Sanitize_ID INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE RLCategories
	MODIFY COLUMN PK_RLCategory_ID INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE CYCategories
	MODIFY COLUMN PK_CYCategory_ID INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE RLIndicators
	MODIFY COLUMN PK_RLIndicators_ID INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE CYIndicators
	MODIFY COLUMN PK_CYIndicators_ID INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE GWIndicators
     MODIFY COLUMN PK_GWIndicator_ID INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE UnprocessedFiles
	MODIFY COLUMN PK_UnprocessedFiles_ID INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE Dynamic_Analysis
	MODIFY COLUMN PK_Dynamic_Analysis_ID INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE Dynamic_Analysis_Sanitizations
	MODIFY COLUMN PK_Dynamic_Analysis_Sanitizations_ID INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE VxStream_Results
	MODIFY COLUMN PK_VxStream_Results_ID INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE Emails
	MODIFY COLUMN PK_Email_ID INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE Recipients
	MODIFY COLUMN PK_Recipient_ID INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE Email_Recipients
	MODIFY COLUMN PK_Email_Recipient_ID INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE Attachments
	MODIFY COLUMN PK_Attachment_ID INTEGER NOT NULL AUTO_INCREMENT;

SET foreign_key_checks = 1;
