SET SQL_SAFE_UPDATES = 0;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE UnprocessedFiles;
TRUNCATE TABLE Sanitize;
TRUNCATE TABLE Analysis;
TRUNCATE TABLE FileAttributes;
SET SQL_SAFE_UPDATES = 1;
SET FOREIGN_KEY_CHECKS = 1;
